version: '3.8'

services:
  backend:
    build: ./backend
    container_name: hivemind-backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    container_name: hivemind-db-production
    image: postgres:15
    env_file:
      - .env
    volumes:
      - hivemind-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  hivemind-db-data: